# Generated by Django 5.2.8 on 2025-11-13 02:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('polera', 'Polera'), ('pantalon', 'Pantalón/Short'), ('accesorio', 'Accesorio')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en el catálogo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar del catálogo')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en sección destacados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('talla', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3, null=True)),
                ('tipo_pantalon', models.CharField(blank=True, choices=[('short', 'Short'), ('pantalon_largo', 'Pantalón Largo'), ('jogger', 'Jogger')], help_text='Solo para pantalones/shorts', max_length=50, null=True)),
                ('material', models.CharField(blank=True, help_text='Solo para accesorios', max_length=100, null=True)),
                ('dimensiones', models.CharField(blank=True, help_text='Solo para accesorios (ej: 20x30cm)', max_length=100, null=True)),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible (solo visible en admin)', validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-destacado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en el carrusel')),
                ('es_principal', models.BooleanField(default=False, help_text='Imagen principal del producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['-es_principal', 'orden'],
            },
        ),
    ]
