# Generated by Django 5.2.8 on 2025-11-13 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_accesorio',
            field=models.IntegerField(default=0, help_text='Stock para accesorios (no tienen tallas)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar en página principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='dimensiones',
            field=models.CharField(blank=True, help_text='Solo para accesorios', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StockTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3)),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad disponible de esta talla', validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_tallas', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Stock por Talla',
                'verbose_name_plural': 'Stock por Tallas',
                'ordering': ['talla'],
                'unique_together': {('producto', 'talla')},
            },
        ),
    ]
